service: tesseract-ocr
frameworkVersion: ">=2.0.0"

plugins:
    - serverless-python-requirements

provider:
  name: aws
  region: eu-west-1
  memorySize: 1769

custom:
  pythonRequirements:
    dockerizePip: true
    dockerFile: Dockerfile

layers:
  tesseractAl1:
    # specify path to layer content
    path: ../../ready-to-use/amazonlinux-1
    compatibleRuntimes:
      - python3.6

functions:
  tesseract-ocr:
    handler: handler.main
    runtime: python3.6
    layers:
      - { Ref: TesseractAl1LambdaLayer }
    events:
      - http:
          path: ocr
          method: post
